#!/usr/bin/env sh

sysctl -w vm.max_map_count=262144

# reset permissions after docker volume remount
chown -R elasticsearch:elasticsearch /var/lib/elasticsearch /opt/elasticsearch

exec s6-setuidgid elasticsearch /opt/elasticsearch/bin/elasticsearch 2>&1
